# Generated by Django 3.0.5 on 2020-04-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='league.Assets')),
            ],
            options={
                'ordering': ['year', 'round', 'pick'],
            },
        ),
        migrations.CreateModel(
            name='LeagueRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=127)),
                ('rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('game_week', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbrev', models.CharField(max_length=100)),
                ('points_for', models.FloatField()),
                ('points_against', models.FloatField()),
                ('place', models.IntegerField()),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Owner')),
            ],
            options={
                'ordering': ['game_week', 'place'],
            },
        ),
        migrations.CreateModel(
            name='PickTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.DraftPick')),
                ('traded_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_from', to='league.Owner')),
                ('traded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_to', to='league.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PastSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('points_for', models.FloatField()),
                ('points_against', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('team', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('taxi', models.BooleanField(default=False)),
                ('rostered', models.BooleanField(default=False)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=8, null=True)),
                ('weight', models.CharField(blank=True, max_length=8, null=True)),
                ('espn_id', models.CharField(blank=True, max_length=125, null=True)),
                ('sleeper_id', models.CharField(blank=True, max_length=125, null=True)),
                ('roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.Assets')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('division', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='league.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('game_week', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbrev', models.CharField(max_length=100)),
                ('points_for', models.FloatField()),
                ('opponent', models.CharField(max_length=100)),
                ('points_against', models.FloatField()),
                ('result', models.IntegerField(default=0)),
                ('point_dif', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Owner')),
            ],
            options={
                'ordering': ['-year', 'game_week'],
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.Owner'),
        ),
    ]
