# Generated by Django 3.0.5 on 2020-04-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200421_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflplayer',
            options={'ordering': ['position', '-tenure']},
        ),
        migrations.AlterModelOptions(
            name='pastseason',
            options={'ordering': ['year', 'place']},
        ),
    ]
