# Generated by Django 3.0.5 on 2020-05-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_dates_ruleproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguerules',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='ruleproposal',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='ruleproposal',
            name='result',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
