# Generated by Django 3.0.5 on 2020-05-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20200507_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='draft_capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_pick', to='league.DraftPick'),
        ),
    ]
