# Generated by Django 3.0.5 on 2020-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_nflplayer_draft_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastseason',
            name='league_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
